name: Code Check with Gradle

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4

      - name: Download Icons
        run: (cd mock && curl -Lo AdobeSpectrumIcons18.woff2 "https://developer.adobe.com/experience-manager/reference-materials/6-5/coral-ui/coralui3/resources/coralui-component-icon/AdobeSpectrumIcons18.woff2?651453a29a2cf87546cdc6215616731e" && curl -Lo AdobeSpectrumIcons24.woff2 "https://developer.adobe.com/experience-manager/reference-materials/6-5/coral-ui/coralui3/resources/coralui-component-icon/AdobeSpectrumIcons24.woff2?b750bfd862e4ef0daea700228de3e788")

      - name: Run checks
        run: ./gradlew playwrightInstall check --continue

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: reports
          path: build/reports/
          retention-days: 30

      - uses: mikepenz/action-junit-report@v5
        if: ${{ !cancelled() }}
        with:
          report_paths: '**/build/**/TEST-*.xml'
