name: Code Check with Gradle

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: gradle/actions/setup-gradle@v4

      - name: Run checks
        run: ./gradlew playwrightInstall check --continue

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: reports
          path: build/reports/
          retention-days: 30
